### ISSUE TITLE
croupier behavior in the example code not correct?

### ISSUE THREAD

**Issue by zw963** [ralsina/croupier#12]
```
# test.cr

require "croupier"

Croupier::Task.new(
  output: "fileA",
  inputs: ["input.txt"],
) {
  puts "task1 running"
  File.read("input.txt").downcase
}

Croupier::Task.new(
  output: "fileB",
  inputs: ["fileA"],
) do
  puts "task2 running"
  File.read("fileA").upcase
end

Croupier::TaskManager.run_tasks
```

Assume we have `input.txt`, with content:

```
Hello
```

Then run it.

```
 ╰─ $ cr run test.cr
task1 running
task2 running

 ╰─ $ \cat fileA
hello

 ╰─ $ \cat fileB
HELLO
```

Until now, everything work as expected.

then, change `input.txt` into:

```
Hello
World
```

run it again.

```
 ╰─ $ cr run test.cr
task1 running

 ╰─ $ \cat fileA
hello
world

 ╰─ $ \cat fileB
HELLO
```

the expected behavior should be, change fileB into:

```
HELLO
WORLD
```

right?

Thanks.

**Comment by ralsina** [comment]
Indeed, looks like a bug!

Looks like the dependency chain

`input.txt -> fileA -> fileB` is not being fully invalidated when input.txt is detected as modified.

**Comment by ralsina** [comment]
Here's what was happening.

When doing a run, we have the tasks to execute in this order because of dependencies:

`[t1, t2]`

When starting execution t1 and t2 are stale because input and fileA are stale.

After executing t1, both input and fileA are not stale anymore because t1 has already updated them, so t2 was not executed.

Solution: not checking for staleness while looping, check only once before executing tasks.

It's merged, I will probably do a release in a couple of hours, since it's an important fix. 

Thanks for the help  finding this!
